# version: '3.8'

# services:
#   # db:
#     # image: mariadb:10.5
#     # # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin 
#     # # command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --character-set-server=utf8
#     # container_name: db
#     # environment:
#     #   MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
#     # volumes:
#     #   - mariadb_data:/var/lib/mysql
#     #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     # ports:
#     #   - "3306:3306"
#     # restart: always
#   db:
#     image: mariadb:latest
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: db_os
#       MYSQL_USER: user
#       MYSQL_PASSWORD: user123@
#     ports:
#       - "33061:3306"
#     volumes:
#       - mariadb_data_1:/var/lib/mysql

#   web:
#     build: .
#     container_name: web
#     # command: >
#     #   sh -c "
#     #   /wait-for-it.sh db 3306 -- 
#     #   python manage.py runserver 0.0.0.0:8000"
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DB_HOST=db
#       - DB_NAME=db_os
#       - DB_USER=root
#       - DB_PASS=root
#       - DB_PORT=3306
#     restart: always

# volumes:
#   mariadb_data_1:

version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_user_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=example_db
      - DB_USER=example_user
      - DB_PASSWORD=example_user_password
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  mariadb_data:
